In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score,KFold
from sklearn.datasets import make_classification
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix

In [2]:
X,y = make_classification(n_samples=500,n_classes=2, n_features=10, n_informative=7)

In [6]:
X[:5,:]

array([[-0.83615891, -2.62935022,  0.02245787, -0.63873755, -3.37424456,
        -0.45707383, -0.74903994, -0.15796854,  0.03236489,  2.50088006],
       [ 0.61637197,  0.65535753, -1.23519868,  0.73518221, -1.28874194,
         0.64597806, -0.51194352, -1.4390347 , -0.72402618,  1.20884948],
       [ 1.44552413,  2.0561213 ,  1.54426277,  2.39772261, -0.47725095,
        -0.46344092, -0.62784646, -1.81458754,  1.87149166,  1.1209365 ],
       [ 2.36166212,  1.99641719, -1.68595616,  0.33641063, -3.07595187,
         5.66485673, -5.42765277,  0.69075216, -1.90078083,  2.74041334],
       [-0.04012671, -0.54349266, -3.82774472,  1.30849939, -0.87770692,
         2.84262707, -2.38069839, -0.53018173, -1.20229415,  0.20545787]])

In [7]:
y[:5]

array([1, 0, 0, 0, 1])

We have to give either train_size or test_size

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.75, random_state=74)

In [12]:
X_train[0]

array([-0.85822522, -0.9236081 , -0.54589631, -0.19754225,  2.15869491,
       -0.47943879,  2.33312558, -0.99601662,  0.79881434, -2.38683907])

# Confusion matrix

split picks data randomly, every tim we will re fresh the code it will give a different selection to uniform it we use **random state**