In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import warnings
warnings.filterwarnings("ignore")

In [4]:
X, y = make_classification(n_samples=500, n_classes=2, n_features=10, n_informative=7)

In [7]:
X[:5, :]

array([[ 3.00248582,  1.34991733,  0.51010063, -0.39337279, -1.93955037,
        -2.34406867, -2.13382727, -6.52687373,  2.21817193,  1.11766181],
       [-2.94785983,  0.1707897 ,  2.57557786, -2.78954935, -0.57859544,
         1.44706764,  1.15852537,  5.95257701, -1.40546931, -0.64298569],
       [ 0.15543422, -1.48071645, -1.24401838,  0.6309004 , -1.58902894,
         0.94658261,  2.51733995,  0.25888088, -0.73412766, -1.14269007],
       [-1.08635169,  0.73547093,  1.41360493, -0.07396153, -1.22685334,
        -1.82210119, -0.99681103, -0.11663966,  1.56332136, -1.0369173 ],
       [-0.6719592 ,  0.76401512, -0.59497322,  1.56147405, -0.41560488,
         2.18323266,  2.66784703,  1.15562087,  0.30007847, -2.47884464]])

In [8]:
y[:5]

array([0, 0, 0, 1, 1])

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.75, random_state=74)

In [44]:
X_train[0]

array([ 0.02539439,  0.60588223,  1.6634156 ,  0.08557707,  0.34408416,
       -0.22057242, -0.66989445,  3.12197115, -2.14135873, -1.38663203])

In [45]:
X_train.shape

(375, 10)

In [46]:
X_test.shape

(125, 10)

In [47]:
y_train.shape

(375,)

In [48]:
y_test.shape

(125,)

In [49]:
model = LogisticRegression()

In [50]:
model.fit(X_train, y_train)

LogisticRegression()

In [51]:
y_pred = model.predict(X_test)

In [52]:
accuracy_score(y_test, y_pred)

0.768

In [54]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.71      0.85      0.78        59
           1       0.84      0.70      0.76        66

    accuracy                           0.77       125
   macro avg       0.78      0.77      0.77       125
weighted avg       0.78      0.77      0.77       125



In [55]:
confusion_matrix(y_test, y_pred)

array([[50,  9],
       [20, 46]], dtype=int64)

In [56]:
93/115

0.808695652173913

In [57]:
50/57

0.8771929824561403

In [58]:
50/65

0.7692307692307693

In [59]:
2*0.8771*0.7692

1.34933064

In [60]:
0.8771+0.7692

1.6463

In [61]:
1.34933064 / 1.6463

0.8196140679098585